Fixed error C2440: 'function': cannot convert from 'int (__cdecl *)(libusb_context *,libusb_device *,libusb_hotplug_event,void *)' to 'libusb_hotplug_callback_fn'
(cherry picked from commit df294acbae42769e55f87613fddd1fabb8a5d378)